context:
  heading: "This is some text..."
default: "regular"
title: "Typography - V&A Sans"
status: wip
variants: [
  {
    "name": "light",
    "label": "Light",
    "context": {
      "name": "light",
      "sizes": [2,3,5]
    }
  },
  {
    "name": "regular",
    "label": "Regular",
    "context": {
      "name": "regular",
      "sizes": [5,6,7,8,9]
    }
  },
  {
    "name": "bold",
    "label": "Bold",
    "context": {
      "name": "bold",
      "sizes": [3,4,5,6,8]
    }
  },
  {
    "name": "semi-bold",
    "label": "Semi-bold",
    "context": {
      "name": "semi-bold",
      "sizes": [1,2,3]
    }
  }
]
