context:
  text: Click me
default: default
title: Buttons
status: wip
variants: [
  {
    "name": "default",
    "label": "Default"
  },
  {
    "name": "arrowed",
    "label": "Arrowed",
    "context": {
      "text": "Read more about this topic",
      "modifiers": ['arrowed']
    }
  },
  {
    "name": "black",
    "context": {
      "text": "Sign up",
      "modifiers": ['black']
    }
  },
  {
    "name": "micro",
    "context": {
      "text": "More info",
      "modifiers": ['micro'],
      "variants": [
        ['micro', 'arrowed'],
        ['micro', 'black'],
        ['micro', 'outlined'],
        ['micro', 'outlined', 'arrowed'],
        ['micro', 'outlined', 'arrowed', 'black']
      ]
    }
  },
  {
    "name": "themed",
    "context": {
      "colors": '@theme-color.colors',
      "text": "Become a V&A member",
      "modifiers": ['arrowed', 'themed']
    }
  },
  {
    "name": "outlined",
    "context": {
      "text": "Book now",
      "modifiers": ['outlined'],
      "variants": [
        ['outlined', 'arrowed'],
        ['outlined', 'black'],
        ['outlined', 'arrowed', 'black'],
        ['outlined', 'micro'],
      ]
    }
  }
]
